### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zaclys**
Hi Nextcloud Team. This is our request to add Zaclys to the list. Thanks a lot !

### CODE REVIEW

**Comment by zaclys** [comment]
Hi,

is there something wrong ? Sorry this is hard for me. I'm not a githuber ands would just add Zaclys as provider please.

Best regards

**Comment by nieebel** [comment]
Could you please provide an English description?

**Comment by zaclys** [comment]
> Could you please provide an English description?

Hi @nieebel

thanks for your reply. If we had to choose only one language, could it be french please ? Because, most of our users are french native people.

Best regards

Here is the requested translated version :  

ZACLYS, ethical and open source web services for individuals and professionals. Cloud, OnlyOffice, Mail, visio and more to discover on Zaclys.com

**Comment by nieebel** [comment]
Hi @zaclys, 
I don't have access to your branch hence I create a new Pull request in a new branch and invited you into the branch in case you ant to change to update it, before the pull request got merged:
https://github.com/nieebel/providers/edit/patch-1/README.md

Here is the new pull request: 
https://github.com/nextcloud/providers/pull/57

Please close this Pull request if the new one is ok for you:
image

**Comment by zaclys** [comment]
Thanks a lot @nieebel ! Approved your new PR. I have to say this github thing is a pure nightmare for me as I'm not a dev :'D

**Pull request closed without merging**
