### PR TITLE
add Zaclys.com

### PR DESCRIPTION
**Pull request by nieebel**
Originally requested by: https://github.com/nextcloud/providers/pull/56

### CODE REVIEW

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Comment by nieebel** [comment]
@jospoortvliet could you please merge this PR?

**Review by zaclys — APPROVED** [review]

**Comment by zaclys** [comment]
@nieebel @jospoortvliet Hi, really lost with this. I approved something somewhere I don't understand. Kind of silly procedure to add an image + text in a list of providers friends. Hope it's ok now :(

Best regards

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Review by zaclys — APPROVED** [review]

**Comment by zaclys** [comment]
@nieebel @jospoortvliet Hi, again I need your help for this. I'm not computer scientist and lost with your github procedures.

Best regards

**Review by zaclys — APPROVED** [review]

**Comment by zaclys** [comment]
@nieebel @jospoortvliet Hi, hope it's ok now. Thanks for your help.
Best regards

**Comment by zaclys** [comment]
Is there still someone here ?

**Review by jospoortvliet — APPROVED** [review]

**Pull request merged**
