### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by yourcloudasia**
Add yourcloud Asia entry.

### CODE REVIEW

**Comment by yourcloudasia** [comment]
Is there anything more that needs to be done here @jospoortvliet?

**Comment by kesselb** [comment]
Wrong button ;) It might be easier to redo the changes as the `README.md` has been changed in the meantime.

**Comment by yourcloudasia** [comment]
That's probably because it took so long to get a response?

**Comment by kesselb** [comment]
> That's probably because it took so long to get a response?

Yes

**Pull request merged**
