### PR TITLE
Added Giebel.IT

### PR DESCRIPTION
**Pull request by Dominion0815**

### CODE REVIEW

**Review by Dominion0815 — COMMENTED** [review]
Signed-off-by: Stefan Giebel <stefan@giebel.it>

**Review by Dominion0815 — COMMENTED** [review]
Signed-off-by: Stefan Giebel <stefan@giebel.it>

**Review by Dominion0815 — COMMENTED** [review]
Signed-off-by: Stefan Giebel <stefan@giebel.it>

**Review by kesselb — APPROVED** [review]

**Comment by kesselb** [comment]
Hi, 

I cannot merge your pr without the dco check.

Try

git rebase HEAD~2 --signoff
git push --force-with-lease origin master

**Pull request merged**
