### PR TITLE
Add CommonsCloud provider

### PR DESCRIPTION
**Pull request by dvdjaco**
The Catalan language doesn't have a Unicode/emoji flag, so I inserted instead an image from Wikimedia Commons (cc-by-sa license).

### CODE REVIEW

**Comment by kesselb** [comment]
image

Not great. Unfortunately the emoji flags are for countries but we use it for languages here. I'm not sure what the current status of language flags is. Only found this old discussion: https://unicode.org/mail-arch/unicode-ml/y2015-m02/0039.html.

**Comment by dvdjaco** [comment]
As far as I know regional flags are possible since the Regional_Indicator property was introduced in Unicode v10 back in 2017, but the Catalan flag hasn't been implemented yet. Inserting the image is a bit of a hack, the alternative is to have languages without a unicode flag as text tags, e.g.:

 :uk: :es: :catalan:

**Comment by jospoortvliet** [comment]
Hmmm, https://github.com/nextcloud/providers/blob/f9e82f53bcd024c2e71d0a1427e639cea8c8801c/README.md looks good for me here, the flag is a bit fuzzy in rendering but life ain't perfect, I do think it is good enough. So I'm good with this.

**Comment by kesselb** [comment]
.

Fine by me. Adding a screenshot from GitHub app just as information.

**Comment by jospoortvliet** [comment]
oh, it's too small on high-dpi systems... yeah, not much I can think to do about that ;-)

**Pull request merged**
