### PR TITLE
Added VoltHosting

### PR DESCRIPTION
**Pull request by rowansc1**
Signed-off-by: Rowan <rowan@volthosting.co.uk>

### CODE REVIEW

**Comment by kesselb** [comment]
Hi,

I cannot merge your pr without the dco check.

Try

git rebase HEAD~2 --signoff
git push --force-with-lease origin master

**Comment by kesselb** [comment]
Hi,

I'm not allowed to push to your fork, could you resolve the conflicts or submit a new pr?

Thanks

**Comment by kesselb** [comment]
Merged via https://github.com/nextcloud/providers/pull/120

**Comment by rowansc1** [comment]
Great, thank you very much :)

**Pull request closed without merging**
