### PR TITLE
Add Hetzner to the list of providers

### PR DESCRIPTION
**Pull request by gurbindersingh**
I have no affiliation to the provider, aside from using their services.

### CODE REVIEW

**Comment by kesselb** [comment]
Thank you :+1: 

Do you have the permission to upload their logo here?

**Comment by kesselb** [comment]
Also the logo should be 600x150 as per https://github.com/nextcloud/providers?tab=readme-ov-file#instructions-to-add-a-provider

**Comment by gurbindersingh** [comment]
> Thank you 👍
> 
> Do you have the permission to upload their logo here?

As far as I know you don't express permission to use a logo if it used for information purposes.

**Comment by gurbindersingh** [comment]
> Also the logo should be 600x150 as per https://github.com/nextcloud/providers?tab=readme-ov-file#instructions-to-add-a-provider

Should be fixed now.

**Pull request closed without merging**
