### PR TITLE
openitstore provider

### PR DESCRIPTION
**Pull request by openitstore**
Logo for Open IT Store Provider

### CODE REVIEW

**Comment by openitstore** [comment]
Hello jos, please find here our page description to our nextcloud offers. Regards

**Comment by jospoortvliet** [comment]
Sorry it took a long time to get merged!

**Comment by kesselb** [comment]
@openitstore change `https://github.com/nextcloud/providers/raw/master/logos/openitstore-logo.png` to `https://raw.githubusercontent.com/nextcloud/providers/master/logos/OpenITStore.png` otherwise the logo is not shown.

**Comment by MorrisJobke** [comment]
> @openitstore change `https://github.com/nextcloud/providers/raw/master/logos/openitstore-logo.png` to `https://raw.githubusercontent.com/nextcloud/providers/master/logos/OpenITStore.png` otherwise the logo is not shown.

https://github.com/nextcloud/providers/commit/7460f5ecf975dc030577d869b644aa71b999899f

**Pull request merged**
